config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /customers/sign_in ...
devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #会員側のルーティング
  scope module: :public do
    resources :addresses, only: [:new, :index, :edit, :create, :update, :destroy ]

    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy ]


    # resource :customers, only: [:edit, :update ]
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/reject_customer' => 'customers#reject_customer'

    root to: 'homes#top'
    get 'homes/about' => 'homes#about'

    resources :items, only: [:index, :show ]

    get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:new, :create, :index, :show ]
    post 'orders/confirm' => 'orders#confirm'

    #resources :registrations, only: [:new, :create ]

    #resources :sessions, only: [:new, :create, :destroy ]
  end
  #管理者側のルーティング
  namespace :admin do

    resources :customers, only: [:index, :show, :edit, :update ]

    resources :genres, only: [:index, :edit, :create, :update ]

    get '' => 'homes#top'

    resources :items, only: [:new, :show, :index, :edit, :create, :update ]

    resources :orders, only: [:show, :update ]

    resources :order_details, only: [:update ]

    #resources :sessions, only: [:new, :create, :destroy ]

  end
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def address_display
    '〒' + postal_code + ' ' + address + ' ' name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  def subtotal
    item.add_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord


end

app/models/item.rb
class Item < ApplicationRecord

  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  has_one_attached :image

# 消費税を加えた商品価格 .roundを使って、小数点を切り上げ
  def add_tax_price
    (self.price * 1.08).round
  end

end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_details, dependent: :destroy

  belongs_to :customer

  def subtotal
    item.add_tax_price * amount
  end

  def order_detail_subtotal
    price_including_tax * quantity
  end

  enum payment_method: {credit_card: 0, transfer: 1 }
  enum order_status:{payment_waiting: 0, payment_confirmation: 1, in_production: 2, delivery_preparation: 3, delivered: 4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum production_status:{production_not_possible: 0, production_pending: 1, in_production: 2, production_complete: 3 }

  def subtotal
    price_including_tax * quantity
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  before_action :authenticate_admin!

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  before_action :authenticate_admin!

  def top
    @orders = Order.page(params[:page]).per(10)
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page]).per(10)
    # @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_item_path(item.id)
  end

  def show
    @item = Item.find(params[:id])

  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_items_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :image )
  end


end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @total = 0
  end

  def update
    order = Order.find(params[:id])
    order.update(order_params)
    if order.order_status == 'payment_confirmation'
      @order_details = order.order_details
      @order_details.update_all(production_status: 1 )
    end
    redirect_to admin_order_path(order.id)
  end

  private

  def order_params
    params.require(:order).permit(:delivery_postal_code, :delivery_address, :delivery_name, :total_payment, :freight, :payment_method, :order_status )
  end

  def order_detail_params
    params.require(:order_detail).permit(:price_including_tax, :quantity, :production_status )
  end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController

  def after_sign_in_path_for(resource)
    admin_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end



  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected





  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base



end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="">

    <h4 class="page-title">商品編集</h4>

    <div>
      <%= form_with model: @item, url: admin_item_path(@item.id), method: :patch do |f| %>

        <div class="row">
          <h5 class="col-sm-4">商品画像</h5>
          <div class="col-sm-8">
            <label>
              <span class="">
                <%= f.file_field :image, class: "image_field", style: "", accept: "image/*" %>
              </span>
            </label>
          </div>
        </div>

        <div class="row">
          <h5 class="col-sm-4">商品名</h5>
          <div class="col-sm-8">
            <%= f.text_field :name, size: "28", placeholder: "商品名" %>
          </div>
        </div>

        <div class="row">
          <h5 class="col-sm-4">商品説明</h5>
          <div class="col-sm-8">
            <%= f.text_area :introduction, size: "30x5", placeholder: "ここに説明文を記述します" %>
          </div>
        </div>

        <div class="row">
          <h5 class="col-sm-4">税抜価格</h5>
          <div class="col-sm-8">
            <%= f.number_field :price, class: "number_field", placeholder: "1000" %>
            <span class="yen">円</span>
          </div>
        </div>

        <div class="row">
          <h5 class="col-sm-4">販売ステータス</h5>
          <div class="col-sm-8">
            <%= f.radio_button :is_active, :true %>
            <%= f.label :is_active, '販売中' %>
            <%= f.radio_button :is_active, :false %>
            <%= f.label :is_active, '販売停止中' %>
          </div>
        </div>
        <div class="row">
          <%= f.submit '変更を保存', class: 'btn btn-success confirm-button', style: "width: 10em;" %>
        </div>
    <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="row">
        <h4 class="page-title">商品一覧</h4>
        <span class="col-7"></span>
        <%= link_to new_admin_item_path, class: "", style: " height: 40px; width: 40px;", method: :get do %>
          <i class="fa-solid fa-circle-plus" style="font-size: 40px; color: #DDD;"></i>
        <% end %>
      </div>
      <table class="table">
        <thead class="thead-color">
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税込価格</th>
            <th></th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
          <tr>
            <td><%= item.id %></td>
            <td>
              <%= link_to admin_item_path(item.id), class: '', method: :get do %>
                <%= item.name %>
              <% end %>
            </td>
            <td><%= item.price %></td>
            <td></td>
            <td>
              <% if item.is_active == true %>
                <div class="text-success font-weight-bold">販売中</div>
              <% else %>
                <div class="text-secondary font-weight-bold">販売停止中</div>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <div class="p-top__paginate">
        <%= paginate @items %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="">

    <h4 class="page-title">商品新規登録</h4>

    <div>
      <%= form_with model: @item, url: admin_items_path, method: :post do |f| %>

        <div class="row">
          <h5 class="col-sm-4">商品画像</h5>
          <div class="col-sm-8">
            <label>
                <%= f.file_field :image, accept: "image/*" %>
            </label>
          </div>
        </div>

        <div class="row">
          <h5 class="col-sm-4">商品名</h5>
          <div class="col-sm-8">
            <%= f.text_field :name, size: "28", placeholder: "商品名" %>
          </div>
        </div>

        <div class="row">
          <h5 class="col-sm-4">商品説明</h5>
          <div class="col-sm-8">
            <%= f.text_area :introduction, size: "31x5", placeholder: "ここに説明文を記入します" %>
          </div>
        </div>

        <div class="row">
          <h5 class="col-sm-4">税抜価格</h5>
          <div class="col-sm-8">
            <%= f.number_field :price, class: "number_field", placeholder: "1000" %><span class="yen">円</span>
          </div>
        </div>

        <div class="row">
          <h5 class="col-sm-4">販売ステータス</h5>
          <div class="col-sm-8">
            <%= f.radio_button :is_active, :true %>
            <%= f.label :is_active, '販売中' %>
            <%= f.radio_button :is_active, :false %>
            <%= f.label :is_active, '販売停止中' %>
          </div>
        </div>
        <div class="row">
          <%= f.submit '新規登録', class: 'btn btn-success confirm-button' %>
        </div>
    <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<h4 class="page-title">商品詳細</h4>
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <%= image_tag @item.image, size: "150x100" %>
    </div>
    <div class="col-md-8">
      <div class="row">
        <div class="col-md-4">商品名</div>
        <div class="col-md-8">
          <%= @item.name %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">商品説明</div>
        <div class="col-md-8">
          <%= @item.introduction %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">税込価格<br>(税抜価格)</div>
        <div class="col-md-8">
          <%= @item.add_tax_price.to_s(:delimited) %>
          (<%= @item.price.to_s(:delimited) %>)円
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">販売ステータス</div>
        <div class="col-md-8">
          <% if @item.is_active == true %>
            <div class="text-success font-weight-bold">販売中</div>
          <% else %>
            <div class="text-secondary font-weight-bold">販売停止中</div>
          <% end %>
        </div>
      </div>
    </div>
    <button type="button" class="btn btn-success confirm-button">
      <%= link_to '編集する', edit_admin_item_path(@item.id), style: "color: white;" %>
    </button>
  </div>
</div>

app/views/admin/orders/show.html.erb
<h4 class="page-title" style="margin-bottom: 20px;">注文履歴詳細</h4>

<div class="container">
  <div class="row customer-date">
    <div class="col-3" style="font-weight: 700;">購入者</div>
    <div>
      <%= link_to admin_customer_path(@order.customer.id), method: :get do %>
        <%= @order.customer.last_name + @order.customer.first_name %>
      <% end %>
    </div>
  </div>
  <div class="row customer-date">
    <div class="col-3" style="font-weight: 700;">注文日</div>
    <div>
      <%= @order.created_at.strftime('%Y/%m/%d') %>
    </div>
  </div>
  <div class="row customer-date">
    <div class="col-3" style="font-weight: 700;">発送先</div>
    <div>
      〒<%= @order.delivery_postal_code %></br>
        <%= @order.delivery_address %></br>
        <%= @order.delivery_name %>
    </div>
  </div>
  <div class="row customer-date">
    <div class="col-3" style="font-weight: 700;">支払方法</div>
    <div>
      <%= @order.payment_method_i18n %>
    </div>
  </div>
  <div class="row customer-date">
    <div class="col-3" style="font-weight: 700;">注文ステータス</div>
    <div>
      <%= form_with model: @order, url: admin_order_path(@order.id), method: :patch do |f| %>
        <%#= f.select :order_status, [["入金待ち",0],["入金確認",1],["製作中",2],["発送準備",3],["発送済み",4]] %>
        <%= f.select :order_status, Order.order_statuses.keys.map {|k| [I18n.t("enums.order.order_status.#{k}"), k]} %>
        <%= f.submit "変更", class: "btn btn-success btn-sm", style: "width: 50px;" %>
      <% end %>
    </div>
  </div>
</div>

<div>
  <table style="display: inline-block; margin-right: 20px; border-bottom: 1px solid #EEE;">
    <thead class="cart-table-head" style="border-bottom: none;">
      <tr>
        <th class="admin-th" style="width: 30%;">商品名</th>
        <th class="admin-th" style="width: 10%;">単価(税込)</th>
        <th class="admin-th" style="width: 10%;">数量</th>
        <th class="admin-th" style="width: 10%;">小計</th>
        <th class="admin-th" style="width: 30%;">製作ステータス</th>
      </tr>
    </thead>
    <% @order_details.each do |order_detail| %>
      <tbody class="cart-table-body" style="border-bottom: none;">
        <tr>
          <td class="admin-td" style="width: 40%;">
            <%= order_detail.item.name %>
          </td>
          <td class="admin-td" style="width: 15%;">
            <%= order_detail.price_including_tax.to_s(:delimited) %>
          </td>
          <td class="admin-td" style="width: 15%">
            <%= order_detail.quantity %>
          </td>
          <td class="admin-td" style="width: 15%;">
            <% price = order_detail.price_including_tax %>
            <% total_price = price.to_i * order_detail.quantity.to_i %>
            <%= total_price.to_s(:delimited) %>
            <%#= order_detail.order_detail_subtotal.to_s(:delimited) %>
          </td>
          <td class="admin-td" style="width: 15%;">
            <%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id), method: :patch do |f| %>
              <%#= f.select :production_status, [["着手不可",0],["製作待ち",1],["製作中",2],["製作完了",3],] %>
              <%= f.select :production_status, OrderDetail.production_statuses.keys.map {|k| [I18n.t("enums.order_detail.production_status.#{k}"), k]} %>
              <%= f.submit "変更", class: "btn btn-success btn-sm", style: "width: 50px;" %>
            <% end %>
          </td>
        </tr>
      </tbody>
    <% end %>
  </table>


  <div class="container" style="display: inline-block; max-width: 200px; margin-top: 30px; padding-bottom: 100px;">
    <div class="row">
      <div style="font-weight:700; width: 50%;">商品合計</div>
      <div class="col"><%= @order.total_payment.to_s(:delimited) %>円</div>
    </div>
    <div class="row">
      <div style="font-weight:700; width: 50%;">送料</div>
      <div class="col"><%= @order.freight.to_s(:delimited) %>円</div>
    </div>
    <div class="row">
      <div style="font-weight:700; width: 50%;">請求金額合計</div>
      <div class="col" style="font-weight:700;">
        <%= (@order.total_payment.to_i + @order.freight.to_i).to_s(:delimited) %>円
      </div>
    </div>
  </div>
</div>