config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /customers/sign_in ...
devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #会員側のルーティング
  scope module: :public do
    resources :addresses, only: [:new, :index, :edit, :create, :update, :destroy ]

    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy ]


    # resource :customers, only: [:edit, :update ]
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/reject_customer' => 'customers#reject_customer'

    root to: 'homes#top'
    get 'homes/about' => 'homes#about'

    resources :items, only: [:index, :show ]

    get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:new, :create, :index, :show ]
    post 'orders/confirm' => 'orders#confirm'

    #resources :registrations, only: [:new, :create ]

    #resources :sessions, only: [:new, :create, :destroy ]
  end
  #管理者側のルーティング
  namespace :admin do

    resources :customers, only: [:index, :show, :edit, :update ]

    resources :genres, only: [:index, :edit, :create, :update ]

    get '' => 'homes#top'

    resources :items, only: [:new, :show, :index, :edit, :create, :update ]

    resources :orders, only: [:show, :update ]

    resources :order_details, only: [:update ]

    #resources :sessions, only: [:new, :create, :destroy ]

  end
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def address_display
    '〒' + postal_code + ' ' + address + ' ' name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  def subtotal
    item.add_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord


end

app/models/item.rb
class Item < ApplicationRecord

  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  has_one_attached :image

# 消費税を加えた商品価格 .roundを使って、小数点を切り上げ
  def add_tax_price
    (self.price * 1.08).round
  end

end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_details, dependent: :destroy

  belongs_to :customer

  def subtotal
    item.add_tax_price * amount
  end

  def order_detail_subtotal
    price_including_tax * quantity
  end

  enum payment_method: {credit_card: 0, transfer: 1 }
  enum order_status:{payment_waiting: 0, payment_confirmation: 1, in_production: 2, delivery_preparation: 3, delivered: 4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum production_status:{production_not_possible: 0, production_pending: 1, in_production: 2, production_complete: 3 }

  def subtotal
    price_including_tax * quantity
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  before_action :authenticate_admin!

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  before_action :authenticate_admin!

  def top
    @orders = Order.page(params[:page]).per(10)
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page]).per(10)
    # @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_item_path(item.id)
  end

  def show
    @item = Item.find(params[:id])

  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_items_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :image )
  end


end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @total = 0
  end

  def update
    order = Order.find(params[:id])
    order.update(order_params)
    if order.order_status == 'payment_confirmation'
      @order_details = order.order_details
      @order_details.update_all(production_status: 1 )
    end
    redirect_to admin_order_path(order.id)
  end

  private

  def order_params
    params.require(:order).permit(:delivery_postal_code, :delivery_address, :delivery_name, :total_payment, :freight, :payment_method, :order_status )
  end

  def order_detail_params
    params.require(:order_detail).permit(:price_including_tax, :quantity, :production_status )
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base



end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<h4 class="page-title">
  <%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細
</h4>

<div class="container">
  <div class="row customer-date">
    <div class="data-title col-md-4">会員ID</div>
    <div class="data-item col-md-8">
      <%= @customer.id %>
    </div>
  </div>

  <%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch do |f| %>

    <div class="row customer-date">
      <div class="data-title col-md-4">氏名</div>
      <div class="data-field col-md-4">
        <%= f.text_field :last_name, class: "form-control", placeholder: "田中" %>
      </div>
      <div class="data-field col-md-4">
        <%= f.text_field :first_name, class: "form-control", placeholder: "太郎" %>
      </div>
    </div>

    <div class="row customer-date">
      <div class="data-title col-md-4">フリガナ</div>
      <div class="data-field col-md-4">
        <%= f.text_field :last_name_kana, class: "form-control", placeholder: "タナカ" %>
      </div>
      <div class="data-field col-md-4">
        <%= f.text_field :first_name_kana, class: "form-control", placeholder: "タロウ" %>
      </div>
    </div>

    <div class="row customer-date">
      <div class="data-title col-md-4">郵便番号</div>
      <div class="data-field col-md-4">
        <%= f.number_field :postal_code, class: "form-control", placeholder: "1234567(ハイフン不要)" %>
      </div>
    </div>

    <div class="row customer-date">
      <div class="data-title col-md-4">住所</div>
      <div class="data-field col-md-4">
        <%= f.text_field :address, class: "form-control" %>
      </div>
    </div>

    <div class="row customer-date">
      <div class="data-title col-md-4">電話番号</div>
      <div class="data-field col-md-4">
        <%= f.number_field :postal_code, class: "form-control", placeholder: "1234567890(ハイフン不要)" %>
      </div>
    </div>

    <div class="row customer-date">
      <div class="data-title col-md-4">メールアドレス</div>
      <div class="data-field col-md-4">
        <%= f.text_field :email, class: "form-control", placeholder: "sample@email.address" %>
      </div>
    </div>

    <div class="row customer-date">
      <div class="data-title col-md-4">会員ステータス</div>
      <div class="data-field col-md-4">
        <%= f.radio_button :is_deleted, :false %>
        <%= f.label :is_deleted, '有効' %>
        <%= f.radio_button :is_deleted, :true %>
        <%= f.label :is_deleted, '退会' %>
      </div>
    </div>

    <div class="row">
      <span class="col-md-4"></span>
      <%= f.submit '変更を保存', class: 'btn btn-success btn-sm', style: "min-width: 120px;" %>
    </div>


  <% end %>

</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h4 class="page-title">会員一覧</h4>
      <table class="table">
        <thead class="thead-color">
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td>
              <%= link_to admin_customer_path(customer.id), class: '', method: :get do %>
                <% name = customer.last_name + customer.first_name %>
                <%= name %>
              <% end %>
            </td>
            <td><%= customer.email %></td>
            <!--<td></td>-->
            <td>
              <% if customer.is_deleted == false %>
                <div class="text-success font-weight-bold">有効</div>
              <% else %>
                <div class="text-secondary font-weight-bold">退会</div>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<h4 class="page-title" style="margin-left: 0;">
  <%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細
</h4>

<div class="container">

  <div class="row customer-date">
    <div class="data-title col-md-4">会員ID</div>
    <div class="data-item col-md-8">
      <%= @customer.id %>
    </div>
  </div>

  <div class="row customer-date">
    <div class="data-title col-md-4">氏名</div>
    <div class="data-item col-md-8">
      <%= @customer.last_name %>"　"<%= @customer.first_name %>
    </div>
  </div>

  <div class="row customer-date">
    <div class="data-title col-md-4">フリガナ</div>
    <div class="data-item col-md-8">
      <%= @customer.last_name_kana %>"　"<%= @customer.first_name_kana %>
    </div>
  </div>

  <div class="row customer-date">
    <div class="data-title col-md-4">郵便番号</div>
    <div class="data-item col-md-8">
      <%= @customer.postal_code %>
    </div>
  </div>

  <div class="row customer-date">
    <div class="data-title col-md-4">住所</div>
    <div class="data-item col-md-8">
      <%= @customer.address %>
    </div>
  </div>

  <div class="row customer-date">
    <div class="data-title col-md-4">電話番号</div>
    <div class="data-item col-md-8">
      <%= @customer.telephone_number %>
    </div>
  </div>

  <div class="row customer-date">
    <div class="data-title col-md-4">メールアドレス</div>
    <div class="data-item col-md-8">
      <%= @customer.email %>
    </div>
  </div>

  <div class="row customer-date">
    <div class="data-title col-md-4">会員ステータス</div>
    <div class="data-item col-md-8">
      <% if @customer.is_deleted == false %>
        <div class="text-success font-weight-bold">有効</div>
      <% else %>
        <div class="text-secondary font-weight-bold">退会</div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <span class="col-md-4"></span>
    <!--<button class="col-md-6">-->
      <%= link_to "編集する", edit_admin_customer_path(@customer.id), class: "btn btn-success", style: "margin-right: 40px;", method: :get %>
    <!--</button>-->
    <!--<button class="col-md-6">-->
      <%= link_to "注文履歴一覧を見る", admin_path, class: "btn btn-primary", style: "min-width: 200px;", method: :get %>
    <!--</button>-->
  </div>
</div>