config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /customers/sign_in ...
devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #会員側のルーティング
  scope module: :public do
    resources :addresses, only: [:new, :index, :edit, :create, :update, :destroy ]

    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy ]


    # resource :customers, only: [:edit, :update ]
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/reject_customer' => 'customers#reject_customer'

    root to: 'homes#top'
    get 'homes/about' => 'homes#about'

    resources :items, only: [:index, :show ]

    get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:new, :create, :index, :show ]
    post 'orders/confirm' => 'orders#confirm'

    #resources :registrations, only: [:new, :create ]

    #resources :sessions, only: [:new, :create, :destroy ]
  end
  #管理者側のルーティング
  namespace :admin do

    resources :customers, only: [:index, :show, :edit, :update ]

    resources :genres, only: [:index, :edit, :create, :update ]

    get '' => 'homes#top'

    resources :items, only: [:new, :show, :index, :edit, :create, :update ]

    resources :orders, only: [:show, :update ]

    resources :order_details, only: [:update ]

    #resources :sessions, only: [:new, :create, :destroy ]

  end
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def address_display
    '〒' + postal_code + ' ' + address + ' ' name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  def subtotal
    item.add_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord


end

app/models/item.rb
class Item < ApplicationRecord

  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  has_one_attached :image

# 消費税を加えた商品価格 .roundを使って、小数点を切り上げ
  def add_tax_price
    (self.price * 1.08).round
  end

end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_details, dependent: :destroy

  belongs_to :customer

  def subtotal
    item.add_tax_price * amount
  end

  def order_detail_subtotal
    price_including_tax * quantity
  end

  enum payment_method: {credit_card: 0, transfer: 1 }
  enum order_status:{payment_waiting: 0, payment_confirmation: 1, in_production: 2, delivery_preparation: 3, delivered: 4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum production_status:{production_not_possible: 0, production_pending: 1, in_production: 2, production_complete: 3 }

  def subtotal
    price_including_tax * quantity
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  before_action :authenticate_admin!

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  before_action :authenticate_admin!

  def top
    @orders = Order.page(params[:page]).per(10)
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page]).per(10)
    # @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_item_path(item.id)
  end

  def show
    @item = Item.find(params[:id])

  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_items_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :image )
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base



end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naganocake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/9a85a3920e.js" crossorigin="anonymous"></script>
  </head>

  <!--<body class="d-flex flex-column h-100">-->
  <body>

    <header>
      <nav class="navbar navbat-expand-md navbar-dark fixed-top bg-white;" style=" z-index: 9999; background-color: white;">
        <div class="header-logo" style="border: 1px solid black; padding: 5px; margin-left: 5%;">
          <%= link_to 'NAGANO CAKE', root_path %>
        </div>
        <% if customer_signed_in? %>
          <div>
            ようこそ、<%= current_customer.last_name %>さん!
          </div>
        <% end %>
        <div class="nav-button justify-content-end">
          <ul class="navbar-nav mr-auto flex-row">
            <% if admin_signed_in? %>
              <!--管理者側表示-->
              <button type="button" class="btn btn-outline-secondary admin-buttom">
                <li class="nav-item">
                  <%= link_to "商品一覧", admin_items_path %>
                </li>
              </button>
              <button type="button" class="btn btn-outline-secondary admin-buttom">
                <li class="nav-item">
                  <%= link_to "会員一覧", admin_customers_path %>
                </li>
              </button>
              <button type="button" class="btn btn-outline-secondary admin-buttom">
                <li class="nav-item">
                  <%= link_to "注文履歴一覧", admin_path %>
                </li>
              </button>
              <!--<button type="button" class="btn btn-outline-secondary admin-buttom">-->
              <!--  <li class="nav-item">-->
                  <%#= link_to "ジャンル一覧", admin_genres_path %>
              <!--  </li>-->
              <!--</button>-->
              <button type="button" class="btn btn-outline-secondary admin-buttom">
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
                </li>
              </button>
            <% end %>

            <% if customer_signed_in? %>
              <!--顧客がログインしているときに表示-->
              <button type="button" class="btn btn-outline-secondary btn-sm">
                <li class="nav-item">
                  <%= link_to "マイページ", customers_my_page_path %>
                </li>
              </button>
              <button type="button" class="btn btn-outline-secondary btn-sm">
                <li class="nav-item">
                  <%= link_to "商品一覧", items_path %>
                </li>
              </button>
              <button type="button" class="btn btn-outline-secondary btn-sm">
                <li class="nav-item">
                  <%= link_to "カート", cart_items_path %>
                </li>
              </button>
              <button type="button" class="btn btn-outline-secondary btn-sm">
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_customer_session_path, method: :delete %>
                </li>
              </button>
            <% end %>

            <% unless signed_in? %>
              <!--誰もログインしていないときに表示-->
              <button type="button" class="btn btn-outline-secondary">
                <li class="nav-item">
                  <%= link_to "About", homes_about_path %>
                </li>
              </button>
              <button type="button" class="btn btn-outline-secondary">
                <li class="nav-item">
                  <%= link_to "商品一覧", items_path %>
                </li>
              </button>
              <button type="button" class="btn btn-outline-secondary">
                <li class="nav-item">
                  <%= link_to "新規登録", new_customer_registration_path %>
                </li>
              </button>
              <button type="button" class="btn btn-outline-secondary">
                <li class="nav-item">
                  <%= link_to "ログイン", new_customer_session_path %>
                </li>
              </button>
            <% end %>

          </ul>
        </div>
      </nav>
    </header>

    <!--<main roll="main" class="flex-shrink-0 md-auto">-->
    <main roll="main">

        <%= yield %>

    </main>

    <footer class="fixed-bottom">
      <div class="container">
        <span style="height: 60px;"></span>
      </div>
    </footer>

  </body>
</html>